'use strict';
(() => {
  const config=window.IDROCLIMA_RELEASE;if(!config?.enabled)return;
  let day=null,status=null,catalog=[],mode='all',query='',blobUrl=null,userId='',polling=false,documentRequest=0,pdfTask=null,pdfGeneration=0,pdfLibrary,pdfObserver=null,restoreFocus=null;
  const documentCache=new Map(), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>crypto.randomUUID(),identity=()=>typeof currentUser!=='undefined'?currentUser:null,yes=v=>v===true||['TRUE','VERO','SI','SÌ','1'].includes(String(v).toUpperCase()),admin=()=>yes(identity()?.isAdmin),canEdit=()=>admin()||yes(identity()?.canEditProcedure);
  const icon=(name)=>'<i class="fa-solid fa-'+name+'" aria-hidden="true"></i>';
  function toast(text){let node=document.querySelector('.idp-toast');if(!node){node=document.createElement('div');node.className='idp-toast';node.setAttribute('role','status');document.body.append(node);}node.textContent=text;node.hidden=false;clearTimeout(node.timer);node.timer=setTimeout(()=>node.hidden=true,6500);}
  async function call(action,data={}){const before=identity()?.sessionToken;if(!before)throw Error('Accedi al portale per consultare le procedure.');const response=await authenticatedFetch(API_URL,{method:'POST',body:JSON.stringify({...data,action})}),result=await response.json();if(identity()?.sessionToken!==before)throw Error('Account cambiato.');if(result.status!=='success')throw Error(result.message||'Procedure non disponibili.');return result;}
  const banner=document.createElement('section');banner.className='idp-banner';banner.hidden=true;banner.setAttribute('aria-label','Procedure della giornata');document.querySelector('#home-screen .main-content')?.prepend(banner);
  const utility=document.createElement('div');utility.className='idp-utility';utility.hidden=true;utility.innerHTML='<button type="button" data-idp="list">'+icon('book-open')+' Procedure di oggi</button><button type="button" data-idp="push">'+icon('bell')+' Attiva notifiche</button><button type="button" data-idp="test">Prova notifica</button><button type="button" data-idp="disable" hidden>Disattiva notifiche</button><button type="button" data-idp="stats" hidden>Statistiche procedure</button>';document.querySelector('#home-screen .main-content')?.append(utility);
  const dialog=document.createElement('dialog');dialog.className='idp-dialog';dialog.setAttribute('aria-label','Procedure operative');document.body.append(dialog);
  function show(){if(!dialog.open){restoreFocus=document.activeElement;document.documentElement.classList.add('idp-open');dialog.showModal();}}
  function stopPdf(){pdfObserver?.disconnect();pdfObserver=null;pdfGeneration++;const old=pdfTask;pdfTask=null;if(old)old.destroy().catch(()=>{});}
  function clear(){documentCache.clear();documentRequest++;stopPdf();day=null;status=null;catalog=[];banner.hidden=true;utility.hidden=true;if(dialog.open)dialog.close();if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=null;}
  function head(title,subtitle='',reader=false){return '<header class="idp-top"><button type="button" class="idp-icon-button" data-idp="close" aria-label="'+(reader?'Torna alle procedure':'Torna al portale')+'">'+icon('arrow-left')+'</button><img src="idroclima-drop-48.png" alt="" width="28" height="28"><div class="idp-title"><h2>'+esc(title)+'</h2>'+(subtitle?'<small>'+esc(subtitle)+'</small>':'')+'</div>'+(reader?'<button type="button" class="idp-icon-button" data-idp="fullscreen" aria-label="Espandi a schermo intero">'+icon('expand')+'</button>':'')+'</header>';}
  function bindClose(reader=false){dialog.querySelector('[data-idp="close"]').onclick=reader?()=>{documentRequest++;stopPdf();renderList();}:()=>dialog.close();const full=dialog.querySelector('[data-idp="fullscreen"]');if(full)full.onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else dialog.requestFullscreen?.().catch(()=>{});};}
  function paint(){banner.hidden=!day?.actionable||day.state!=='pending';if(!banner.hidden){banner.innerHTML='<span class="idp-mark">'+icon('book-open')+'</span><div class="idp-copy"><strong>Le procedure per la tua giornata</strong><p>'+day.procedures.length+' documenti collegati ai lavori di oggi</p></div><div class="idp-actions"><button class="idp-button primary" data-idp="open">Consulta '+icon('arrow-right')+'</button><button class="idp-icon-button" data-idp="dismiss" aria-label="Ignora avviso per oggi">'+icon('xmark')+'</button></div>';banner.querySelector('[data-idp="open"]').onclick=()=>openList('today');banner.querySelector('[data-idp="dismiss"]').onclick=async()=>{try{await record('dismiss');day.state='dismissed';paint();}catch(e){toast(e.message);}};}utility.hidden=!status?.enabled;utility.querySelector('[data-idp="stats"]').hidden=!admin();utility.querySelector('[data-idp="test"]').hidden=!status?.pushEnabled;utility.querySelector('[data-idp="push"]').disabled=!status?.pushEnabled;}
  async function record(type,procedureId='',context=day){await call('PROCEDURES_EVENT',{id:uid(),type,procedureId,dayKey:context?.key||'',revision:context?.revision||''});}
  async function refresh(){if(polling||document.hidden||dialog.open)return;if(!identity()?.sessionToken){clear();return;}polling=true;try{const id=String(identity().id||identity().ID_UTENTE);if(id!==userId){clear();userId=id;}status=await call('PROCEDURES_STATUS');day=status.day;paint();}catch(e){banner.hidden=true;utility.hidden=true;}finally{polling=false;}}
  function loading(title){dialog.classList.remove('idp-reading');dialog.innerHTML=head(title)+'<main class="idp-loading" role="status">'+icon('circle-notch fa-spin')+'<span>Caricamento…</span></main>';bindClose();show();}
  async function openList(wanted='today'){documentRequest++;stopPdf();const request=documentRequest;mode=wanted==='today'&&day?'today':'all';query='';loading('Procedure');try{const result=await call('PROCEDURES_CATALOG');if(request!==documentRequest||!dialog.open)return;catalog=result.procedures;renderList();const context=mode==='today'?day:null;record('list_open','',context).then(()=>{if(context&&day?.revision===context.revision){day.state='opened';paint();}}).catch(e=>toast('Apertura non registrata: '+e.message));}catch(e){if(request===documentRequest){dialog.innerHTML=head('Procedure')+'<main class="idp-content"><p class="idp-empty">'+esc(e.message)+'</p><button class="idp-button primary" data-idp="retry">Riprova</button></main>';bindClose();dialog.querySelector('[data-idp="retry"]').onclick=()=>openList(wanted);}}}
  function renderRows(){const source=mode==='today'?(day?.procedures||[]):catalog,term=query.toLocaleLowerCase('it').trim(),docs=source.filter(d=>!term||[d.title,...(d.keywords||[])].join(' ').toLocaleLowerCase('it').includes(term)),grid=dialog.querySelector('.idp-grid');grid.innerHTML=docs.length?docs.map(d=>'<article class="idp-card"><span class="idp-document-icon">'+icon('file-lines')+'</span><div class="idp-card-copy"><h3>'+esc(d.title)+'</h3><div class="idp-tags">'+(d.matchedKeywords||d.keywords||[]).map(k=>'<span class="idp-tag">'+esc(k)+'</span>').join('')+'</div></div>'+(canEdit()?'<button class="idp-icon-button" data-keywords="'+esc(d.id)+'" aria-label="Modifica parole chiave: '+esc(d.title)+'">'+icon('tags')+'</button>':'')+'<button class="idp-icon-button idp-open-document" data-document="'+esc(d.id)+'" aria-label="Apri '+esc(d.title)+'">'+icon('chevron-right')+'</button></article>').join(''):'<div class="idp-empty">'+(term?'Nessuna procedura trovata.':'Nessuna procedura collegata. Consulta il catalogo completo.')+'</div>';dialog.querySelector('[data-idp="count"]').textContent=docs.length+' procedure';grid.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>openDocument(b.dataset.document));grid.querySelectorAll('[data-keywords]').forEach(b=>b.onclick=()=>editKeywords(b.dataset.keywords));}
  function renderList(){stopPdf();dialog.classList.remove('idp-reading');dialog.innerHTML=head('Procedure','Idroclima Service')+'<main class="idp-content"><div class="idp-controls"><label class="idp-search">'+icon('magnifying-glass')+'<input type="search" aria-label="Cerca una procedura" placeholder="Cerca per titolo o parola chiave" value="'+esc(query)+'"></label><div class="idp-tabs" role="group" aria-label="Filtra procedure"><button class="idp-tab" aria-pressed="'+(mode==='all')+'" data-idp="all">Tutte</button><button class="idp-tab" aria-pressed="'+(mode==='today')+'" data-idp="today" '+(!day?'disabled':'')+'>Oggi'+(day?' · '+day.procedures.length:'')+'</button></div><span class="idp-count" data-idp="count" aria-live="polite"></span></div><div class="idp-grid"></div></main>';bindClose();dialog.querySelector('[data-idp="today"]').onclick=()=>{mode='today';renderList();};dialog.querySelector('[data-idp="all"]').onclick=()=>{mode='all';renderList();};dialog.querySelector('input').oninput=e=>{query=e.target.value;renderRows();};renderRows();}
  function editKeywords(id){const doc=catalog.find(d=>d.id===id);if(!doc||!canEdit())return;dialog.innerHTML=head('Parole chiave',doc.title)+'<main class="idp-content idp-editor"><label for="idp-keywords">Parole chiave della procedura</label><textarea id="idp-keywords" rows="5" maxlength="4000">'+esc((doc.keywords||[]).join(', '))+'</textarea><p>Separa le parole chiave con una virgola. Verranno cercate nel titolo e nella descrizione degli appuntamenti.</p><div class="idp-actions"><button class="idp-button" data-idp="cancel">Annulla</button><button class="idp-button primary" data-idp="save">Salva parole chiave</button></div></main>';dialog.querySelector('[data-idp="close"]').onclick=renderList;dialog.querySelector('[data-idp="cancel"]').onclick=renderList;dialog.querySelector('[data-idp="save"]').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const keywords=[...new Set(dialog.querySelector('textarea').value.split(',').map(k=>k.trim()).filter(Boolean))];await call('SAVE_PROCEDURE_KEYWORDS',{fileId:id,keywords});doc.keywords=keywords;toast('Parole chiave salvate.');renderList();}catch(e){toast(e.message);button.disabled=false;}};}
  async function renderPdf(url,host){stopPdf();const generation=pdfGeneration;try{pdfLibrary=pdfLibrary||import('./pdf.min.mjs');const lib=await pdfLibrary;if(generation!==pdfGeneration)return;lib.GlobalWorkerOptions.workerSrc=new URL('pdf.worker.min.mjs',location.href).href;pdfTask=lib.getDocument({url,isEvalSupported:false});const pdf=await pdfTask.promise;if(generation!==pdfGeneration)return;let pageNumber=1,zoom=1,fit='width',rendering=false,resizePending=false;host.innerHTML='<div class="idp-page-viewport"><canvas aria-label="Pagina della procedura"></canvas></div><nav class="idp-reader-toolbar" aria-label="Controlli della procedura"><button class="idp-icon-button" data-pdf="prev" aria-label="Pagina precedente">'+icon('chevron-left')+'</button><span data-pdf="count" role="status"></span><button class="idp-icon-button" data-pdf="next" aria-label="Pagina successiva">'+icon('chevron-right')+'</button><span class="idp-toolbar-separator"></span><button class="idp-icon-button" data-pdf="minus" aria-label="Riduci zoom">'+icon('minus')+'</button><button class="idp-icon-button" data-pdf="plus" aria-label="Aumenta zoom">'+icon('plus')+'</button><button class="idp-icon-button" data-pdf="fit" aria-label="Adatta pagina allo schermo">'+icon('arrows-to-dot')+'</button></nav>';const canvas=host.querySelector('canvas'),viewportHost=host.querySelector('.idp-page-viewport'),buttons=host.querySelectorAll('button');async function draw(){if(generation!==pdfGeneration)return;if(rendering){resizePending=true;return;}rendering=true;buttons.forEach(b=>b.disabled=true);try{const page=await pdf.getPage(pageNumber);if(generation!==pdfGeneration)return;const base=page.getViewport({scale:1}),width=Math.max(120,viewportHost.clientWidth-12),height=Math.max(120,viewportHost.clientHeight-12),fitScale=fit==='page'?Math.min(width/base.width,height/base.height):width/base.width,scale=Math.min(fitScale*zoom,4),viewport=page.getViewport({scale}),ratio=Math.min(devicePixelRatio||1,2,Math.sqrt(8000000/(viewport.width*viewport.height)));canvas.width=Math.ceil(viewport.width*ratio);canvas.height=Math.ceil(viewport.height*ratio);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';await page.render({canvasContext:canvas.getContext('2d'),viewport,transform:ratio===1?null:[ratio,0,0,ratio,0,0]}).promise;if(generation===pdfGeneration)host.querySelector('[data-pdf="count"]').textContent=pageNumber+' / '+pdf.numPages;}finally{rendering=false;if(generation===pdfGeneration){buttons.forEach(b=>b.disabled=false);host.querySelector('[data-pdf="prev"]').disabled=pageNumber===1;host.querySelector('[data-pdf="next"]').disabled=pageNumber===pdf.numPages;if(resizePending){resizePending=false;draw().catch(failed);}}}}function failed(){if(generation===pdfGeneration)host.innerHTML='<p class="idp-reader-error">Anteprima non disponibile. Puoi aprire il PDF dal menu qui sotto.</p>';}
    const actions={prev:()=>{if(pageNumber>1)pageNumber--;},next:()=>{if(pageNumber<pdf.numPages)pageNumber++;},minus:()=>zoom=Math.max(.5,zoom-.25),plus:()=>zoom=Math.min(3,zoom+.25),fit:()=>{fit=fit==='width'?'page':'width';zoom=1;}};buttons.forEach(b=>b.onclick=()=>{if(!rendering){actions[b.dataset.pdf]();viewportHost.scrollTo(0,0);draw().catch(failed);}});const observer=pdfObserver=new ResizeObserver(()=>{if(generation!==pdfGeneration){observer.disconnect();return;}draw().catch(failed);});observer.observe(viewportHost);await draw();}catch(e){if(generation===pdfGeneration)host.innerHTML='<p class="idp-reader-error">Anteprima non disponibile. Puoi aprire il PDF dal menu qui sotto.</p>';}}
  async function openDocument(id){documentRequest++;const request=documentRequest;loading('Apertura procedura');try{const account=identity()?.sessionToken,doc=catalog.find(d=>d.id===id)||day?.procedures?.find(d=>d.id===id),key=account+'|'+id,cached=documentCache.get(key),valid=cached&&cached.expires>Date.now()?cached:null,response=await call('PROCEDURES_DOCUMENT',{id,knownVersion:valid?.result.document.version||''}),result=response.notModified&&valid?valid.result:response;if(request!==documentRequest||account!==identity()?.sessionToken||!dialog.open)return;if(result.pdf){documentCache.set(key,{result,expires:Date.now()+300000});while(documentCache.size>3)documentCache.delete(documentCache.keys().next().value);}if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=null;if(result.pdf)blobUrl=URL.createObjectURL(new Blob([Uint8Array.from(atob(result.pdf),c=>c.charCodeAt(0))],{type:'application/pdf'}));dialog.classList.add('idp-reading');dialog.innerHTML=head(result.document.title,'Procedura operativa',true)+'<main class="idp-reader-main">'+(blobUrl?'<div id="idp-pdf-reader" class="idp-pdf-reader" role="region" aria-label="Lettore PDF"><p class="idp-loading" role="status">Preparazione pagina…</p></div>':'<div class="idp-reader-error"><p>'+esc(result.notice||'Anteprima non disponibile.')+'</p><a class="idp-button primary" href="'+esc(result.document.url)+'" target="_blank" rel="noopener">Apri presentazione</a></div>')+'</main>'+(blobUrl?'<footer class="idp-reader-footer"><a href="'+blobUrl+'" target="_blank" rel="noopener">'+icon('arrow-up-right-from-square')+' Apri PDF esterno</a></footer>':'');bindClose(true);if(blobUrl)renderPdf(blobUrl,dialog.querySelector('#idp-pdf-reader'));record('document_open',id,mode==='today'?day:null).catch(e=>toast('Apertura non registrata: '+e.message));}catch(e){if(request===documentRequest){dialog.classList.remove('idp-reading');dialog.innerHTML=head('Procedura')+'<main class="idp-content"><p class="idp-empty">'+esc(e.message)+'</p><button class="idp-button primary" data-idp="back">Torna alle procedure</button></main>';bindClose(true);dialog.querySelector('[data-idp="back"]').onclick=renderList;}}}
  dialog.addEventListener('close',()=>{documentRequest++;stopPdf();document.documentElement.classList.remove('idp-open');if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=null;if(document.fullscreenElement===dialog)document.exitFullscreen?.();restoreFocus?.focus?.();});
  window.IdroclimaOpenProcedures=()=>openList('all');window.IdroclimaCloseProcedures=clear;

  function keyBytes(value){const raw=atob(value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4));return Uint8Array.from(raw,c=>c.charCodeAt(0));}
  async function pushRegistration(){if(!isSecureContext||!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window))throw Error('Per le notifiche serve la PWA su HTTPS. Su iPhone aggiungila alla schermata Home.');return navigator.serviceWorker.ready;}
  utility.querySelector('[data-idp="push"]').onclick=async()=>{try{if(!status?.pushEnabled||!status.publicKey)throw Error('Il servizio di invio push deve essere configurato. L’avviso in-app resta disponibile.');if(!isSecureContext||!('Notification' in window)||!('PushManager' in window))throw Error('Apri la PWA su HTTPS; su iPhone aggiungila alla schermata Home.');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Notifiche non consentite. L’avviso in-app resta disponibile.');const reg=await pushRegistration();let sub=await reg.pushManager.getSubscription();if(sub&&sub.options.applicationServerKey){const expected=keyBytes(status.publicKey),actual=new Uint8Array(sub.options.applicationServerKey);if(expected.length!==actual.length||expected.some((b,i)=>b!==actual[i])){await sub.unsubscribe();sub=null;}}sub=sub||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(status.publicKey)});await call('PROCEDURES_SUBSCRIBE',{subscription:sub.toJSON()});(reg.active||reg.waiting)?.postMessage({type:'IDROCLIMA_PUSH_ACCOUNT',userId:String(identity()?.id||identity()?.ID_UTENTE)});utility.querySelector('[data-idp="disable"]').hidden=false;toast('Notifiche attivate per questo account.');}catch(e){toast(e.message);}};
  utility.querySelector('[data-idp="test"]').onclick=async()=>{try{await call('PROCEDURES_TEST_PUSH');toast('Invio richiesto. Puoi chiudere la PWA e controllare la notifica.');}catch(e){toast(e.message);}};
  utility.querySelector('[data-idp="disable"]').onclick=async()=>{try{const reg=await pushRegistration(),sub=await reg.pushManager.getSubscription();if(sub){await call('PROCEDURES_UNSUBSCRIBE',{endpoint:sub.endpoint});await sub.unsubscribe();}utility.querySelector('[data-idp="disable"]').hidden=true;toast('Notifiche disattivate.');}catch(e){toast(e.message);}};
  utility.querySelector('[data-idp="list"]').onclick=()=>openList('today');
  utility.querySelector('[data-idp="stats"]').onclick=async()=>{try{const data=await call('PROCEDURES_STATS');stopPdf();dialog.classList.remove('idp-reading');dialog.innerHTML=head('Statistiche procedure','Ultimi 30 giorni')+'<main class="idp-content"><p>Le aperture non certificano la lettura completa.</p><div class="idp-table-wrap"><table class="idp-table"><thead><tr><th>Tecnico</th><th>Elenchi</th><th>Documenti</th><th>Ignorati</th></tr></thead><tbody>'+data.users.map(u=>'<tr><td>'+esc(u.name)+'</td><td>'+u.list_open+'</td><td>'+u.document_open+'</td><td>'+u.dismiss+'</td></tr>').join('')+'</tbody></table></div></main>';bindClose();show();}catch(e){toast(e.message);}};
  document.getElementById('btn-logout')?.addEventListener('click',()=>{clear();navigator.serviceWorker?.ready.then(reg=>{reg.active?.postMessage({type:'IDROCLIMA_PUSH_ACCOUNT',userId:''});return reg.pushManager?.getSubscription();}).then(sub=>sub?.unsubscribe()).catch(()=>{});});
  new MutationObserver(()=>{if(document.getElementById('home-screen').classList.contains('hidden')&&!identity())clear();else if(!document.getElementById('home-screen').classList.contains('hidden'))refresh();}).observe(document.getElementById('home-screen'),{attributes:true,attributeFilter:['class']});
  window.addEventListener('focus',refresh);setInterval(refresh,60000);refresh();
  navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='IDROCLIMA_PROCEDURES_OPEN')window.dispatchEvent(new Event('IDROCLIMA_PROCEDURES_OPEN'));});
  window.addEventListener('IDROCLIMA_PROCEDURES_OPEN',async()=>{await refresh();await openList('today');});
  if(new URLSearchParams(location.search).get('procedures')==='today'){const wait=setInterval(()=>{if(identity()?.sessionToken){clearInterval(wait);refresh().then(()=>openList('today'));}},1000);setTimeout(()=>clearInterval(wait),120000);}
  window.IdroclimaPrepareTechnicalLink=async(appId,url)=>{if(config.technicalBridgeEnabled!==true||String(appId)!==String(config.technicalAppId)||!config.technicalUrl)return url;const target=new URL(config.technicalUrl);try{const data=await call('PROCEDURES_TICKET');if(data.ticket)target.searchParams.set('proc_ticket',data.ticket);}catch(e){toast('Procedure automatiche non collegate: '+e.message);}return target.href;};
})();
