'use strict';
(() => {
  const config=window.IDROCLIMA_RELEASE;if(!config?.enabled)return;
  let day=null,status=null,catalog=[],mode='today',query='',blobUrl=null,busy=false,userId='',polling=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>crypto.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
  const identity=()=>typeof currentUser!=='undefined'?currentUser:null;
  function toast(text){let node=document.querySelector('.idp-toast');if(!node){node=document.createElement('div');node.className='idp-toast';node.setAttribute('role','status');document.body.append(node);}node.textContent=text;node.hidden=false;clearTimeout(node.timer);node.timer=setTimeout(()=>node.hidden=true,6500);}
  async function call(action,data={}){const before=identity()?.sessionToken;if(!before)throw Error('Accedi al portale per consultare le procedure.');const response=await authenticatedFetch(API_URL,{method:'POST',body:JSON.stringify({...data,action})});const result=await response.json();if(identity()?.sessionToken!==before)throw Error('Account cambiato.');if(result.status!=='success')throw Error(result.message||'Procedure non disponibili.');return result;}
  const banner=document.createElement('section');banner.className='idp-banner';banner.hidden=true;banner.setAttribute('aria-label','Procedure della giornata');document.querySelector('#home-screen .main-content')?.prepend(banner);
  const utility=document.createElement('div');utility.className='idp-utility';utility.innerHTML='<button type="button" data-idp="list">Procedure della giornata</button><button type="button" data-idp="push">Attiva notifiche</button><button type="button" data-idp="test">Prova notifica</button><button type="button" data-idp="disable" hidden>Disattiva notifiche</button><button type="button" data-idp="stats" hidden>Statistiche procedure</button>';document.querySelector('#home-screen .main-content')?.append(utility);
  const dialog=document.createElement('dialog');dialog.className='idp-dialog';dialog.setAttribute('aria-label','Procedure operative');document.body.append(dialog);
  function clear(){day=null;status=null;catalog=[];banner.hidden=true;utility.hidden=true;if(dialog.open)dialog.close();if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=null;}
  function head(title,subtitle=''){return '<header class="idp-top"><button type="button" class="idp-button" data-idp="close">← Torna</button><div class="idp-title"><h2>'+esc(title)+'</h2><small>'+esc(subtitle)+'</small></div></header>';}
  function bindClose(){dialog.querySelector('[data-idp="close"]').onclick=()=>dialog.close();}
  function paint(){banner.hidden=!day?.actionable||day.state!=='pending';if(!banner.hidden){banner.innerHTML='<span class="idp-mark" aria-hidden="true">📚</span><div class="idp-copy"><strong>Procedure per i lavori di oggi</strong><p>'+day.procedures.length+' documenti collegati alla giornata.</p></div><div class="idp-actions"><button class="idp-button primary" data-idp="open">Apri procedure</button><button class="idp-button quiet" data-idp="dismiss">Ignora per oggi</button></div>';banner.querySelector('[data-idp="open"]').onclick=openList;banner.querySelector('[data-idp="dismiss"]').onclick=async()=>{try{await record('dismiss');day.state='dismissed';paint();}catch(e){toast(e.message);}};}utility.hidden=!status?.enabled;utility.querySelector('[data-idp="stats"]').hidden=!(identity()?.isAdmin===true||['TRUE','Vero'].includes(identity()?.isAdmin));utility.querySelector('[data-idp="push"]').textContent=status?.pushEnabled?'Attiva notifiche':'Notifiche: servizio da configurare';}
  async function record(type,procedureId=''){const data={id:uid(),type,procedureId,dayKey:day?.key||'',revision:day?.revision||''};await call('PROCEDURES_EVENT',data);}
  async function refresh(){if(polling||document.hidden||dialog.open)return;const current=identity();if(!current?.sessionToken){clear();return;}polling=true;try{const id=String(current.id||current.ID_UTENTE);if(id!==userId){clear();userId=id;}status=await call('PROCEDURES_STATUS');day=status.day;paint();}catch(e){banner.hidden=true;utility.hidden=true;}finally{polling=false;}}
  async function openList(){try{catalog=(await call('PROCEDURES_CATALOG')).procedures;mode=day?'today':'all';query='';renderList();if(!dialog.open)dialog.showModal();if(day){await record('list_open');day.state='opened';paint();}}catch(e){toast(e.message);}}
  function renderList(){const source=mode==='today'?(day?.procedures||[]):catalog,term=query.toLowerCase().trim(),docs=source.filter(d=>!term||[d.title,...d.keywords].join(' ').toLowerCase().includes(term));dialog.innerHTML=head('Procedure della giornata',day?day.date+' · squadra '+day.team:'Catalogo procedure')+'<main class="idp-content"><div class="idp-controls"><input type="search" aria-label="Cerca una procedura" placeholder="Cerca…" value="'+esc(query)+'"><button class="idp-button '+(mode==='today'?'primary':'')+'" data-idp="today">Per la giornata</button><button class="idp-button '+(mode==='all'?'primary':'')+'" data-idp="all">Tutte</button></div><div class="idp-grid">'+(docs.length?docs.map(d=>'<article class="idp-card"><h3>'+esc(d.title)+'</h3><div class="idp-tags">'+(d.matchedKeywords||d.keywords).map(k=>'<span class="idp-tag">'+esc(k)+'</span>').join('')+'</div><footer><small>Aggiornata '+esc(new Date(Number(d.version)).toLocaleDateString('it-IT'))+'</small><button class="idp-button primary" data-document="'+esc(d.id)+'">Apri</button></footer></article>').join(''):'<div class="idp-empty">Nessuna procedura collegata. Puoi consultare il catalogo completo.</div>')+'</div></main>';bindClose();dialog.querySelector('[data-idp="today"]').onclick=()=>{mode='today';renderList();};dialog.querySelector('[data-idp="all"]').onclick=()=>{mode='all';renderList();};dialog.querySelector('input').oninput=e=>{query=e.target.value;renderList();const input=dialog.querySelector('input');input.focus();input.setSelectionRange(query.length,query.length);};dialog.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>openDocument(b.dataset.document));}
  async function openDocument(id){if(busy)return;busy=true;try{const result=await call('PROCEDURES_DOCUMENT',{id});if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=null;if(result.pdf){const bytes=Uint8Array.from(atob(result.pdf),c=>c.charCodeAt(0));blobUrl=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));}dialog.innerHTML=head(result.document.title)+'<main class="idp-content">'+(blobUrl?'<iframe class="idp-pdf" title="'+esc(result.document.title)+'" src="'+blobUrl+'"></iframe>':'<p class="idp-note">'+esc(result.notice)+'</p>')+'<div class="idp-actions"><button class="idp-button" data-idp="back">Elenco</button>'+(blobUrl?'<a class="idp-button primary" href="'+blobUrl+'" target="_blank" rel="noopener">Apri PDF</a><a class="idp-button" href="'+blobUrl+'" download="procedura.pdf">Scarica PDF</a>':'')+'<a class="idp-button quiet" href="'+esc(result.document.url)+'" target="_blank" rel="noopener">Originale Drive</a></div></main>';bindClose();dialog.querySelector('[data-idp="back"]').onclick=renderList;if(!dialog.open)dialog.showModal();await record('document_open',id);}catch(e){toast(e.message);}finally{busy=false;}}
  dialog.addEventListener('close',()=>{if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=null;});
  function keyBytes(value){const raw=atob(value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4));return Uint8Array.from(raw,c=>c.charCodeAt(0));}
  async function pushRegistration(){if(!isSecureContext||!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window))throw Error('Per le notifiche serve la PWA su HTTPS. Su iPhone aggiungila alla schermata Home.');return navigator.serviceWorker.ready;}
  utility.querySelector('[data-idp="push"]').onclick=async()=>{try{if(!status?.pushEnabled||!status.publicKey)throw Error('Il servizio di invio push deve essere configurato. L’avviso in-app resta disponibile.');if(!isSecureContext||!('Notification' in window)||!('PushManager' in window))throw Error('Apri la PWA su HTTPS; su iPhone aggiungila alla schermata Home.');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Notifiche non consentite. L’avviso in-app resta disponibile.');const reg=await pushRegistration();let sub=await reg.pushManager.getSubscription();if(sub&&sub.options.applicationServerKey){const expected=keyBytes(status.publicKey),actual=new Uint8Array(sub.options.applicationServerKey);if(expected.length!==actual.length||expected.some((b,i)=>b!==actual[i])){await sub.unsubscribe();sub=null;}}sub=sub||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(status.publicKey)});await call('PROCEDURES_SUBSCRIBE',{subscription:sub.toJSON()});(reg.active||reg.waiting)?.postMessage({type:'IDROCLIMA_PUSH_ACCOUNT',userId:String(identity()?.id||identity()?.ID_UTENTE)});utility.querySelector('[data-idp="disable"]').hidden=false;toast('Notifiche attivate per questo account.');}catch(e){toast(e.message);}};
  utility.querySelector('[data-idp="test"]').onclick=async()=>{try{await call('PROCEDURES_TEST_PUSH');toast('Invio richiesto. Puoi chiudere la PWA e controllare la notifica.');}catch(e){toast(e.message);}};
  utility.querySelector('[data-idp="disable"]').onclick=async()=>{try{const reg=await pushRegistration(),sub=await reg.pushManager.getSubscription();if(sub){await call('PROCEDURES_UNSUBSCRIBE',{endpoint:sub.endpoint});await sub.unsubscribe();}utility.querySelector('[data-idp="disable"]').hidden=true;toast('Notifiche disattivate.');}catch(e){toast(e.message);}};
  utility.querySelector('[data-idp="list"]').onclick=openList;
  utility.querySelector('[data-idp="stats"]').onclick=async()=>{try{const data=await call('PROCEDURES_STATS');dialog.innerHTML=head('Statistiche procedure','Ultimi 30 giorni')+'<main class="idp-content"><p>Le aperture non certificano la lettura completa.</p><div class="idp-table-wrap"><table class="idp-table"><thead><tr><th>Tecnico</th><th>Elenchi</th><th>Documenti</th><th>Ignorati</th></tr></thead><tbody>'+data.users.map(u=>'<tr><td>'+esc(u.name)+'</td><td>'+u.list_open+'</td><td>'+u.document_open+'</td><td>'+u.dismiss+'</td></tr>').join('')+'</tbody></table></div></main>';bindClose();if(!dialog.open)dialog.showModal();}catch(e){toast(e.message);}};
  document.getElementById('btn-logout')?.addEventListener('click',()=>{clear();navigator.serviceWorker?.ready.then(reg=>{reg.active?.postMessage({type:'IDROCLIMA_PUSH_ACCOUNT',userId:''});return reg.pushManager?.getSubscription();}).then(sub=>sub?.unsubscribe()).catch(()=>{});});
  new MutationObserver(()=>{if(document.getElementById('home-screen').classList.contains('hidden')&&!identity())clear();else if(!document.getElementById('home-screen').classList.contains('hidden'))refresh();}).observe(document.getElementById('home-screen'),{attributes:true,attributeFilter:['class']});
  window.addEventListener('focus',refresh);setInterval(refresh,60000);refresh();
  navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='IDROCLIMA_PROCEDURES_OPEN')window.dispatchEvent(new Event('IDROCLIMA_PROCEDURES_OPEN'));});
  window.addEventListener('IDROCLIMA_PROCEDURES_OPEN',async()=>{await refresh();await openList();});
  if(new URLSearchParams(location.search).get('procedures')==='today'){const wait=setInterval(()=>{if(identity()?.sessionToken){clearInterval(wait);refresh().then(openList);}},1000);setTimeout(()=>clearInterval(wait),120000);}
  window.IdroclimaPrepareTechnicalLink=async(appId,url)=>{if(String(appId)!==String(config.technicalAppId)||!config.technicalUrl)return url;const target=new URL(config.technicalUrl);try{const data=await call('PROCEDURES_TICKET');if(data.ticket)target.searchParams.set('proc_ticket',data.ticket);}catch(e){toast('Procedure automatiche non collegate: '+e.message);}return target.href;};
})();
